name: Build & Deploy Lambdas

on:
  push:
    branches: [main]

env:
  ARTIFACT_BUCKET: newsfeed-lambda-artifacts
  AWS_REGION: eu-west-1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda: [fetcher, filter, ingest, ingest_api, retrieve]

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Update Poetry lock file
        run: poetry lock

      - name: Install dependencies and run tests
        run: |
          poetry install --no-root
          poetry run pytest

      - name: Ensure artifact bucket exists (idempotent)
        run: |
          aws s3api head-bucket --bucket "$ARTIFACT_BUCKET" 2>/dev/null || \
          aws s3 mb "s3://$ARTIFACT_BUCKET"

      - name: Package Lambdas
        run: |
          cd src/lambdas/${{ matrix.lambda }}
          pip install -r requirements.txt -t .
          zip -r ../../${{ matrix.lambda }}.zip .

      - name: Upload artifact to S3
        run: |
          aws s3 cp ../../${{ matrix.lambda }}.zip \
            s3://$ARTIFACT_BUCKET/${{ matrix.lambda }}-${{ github.sha }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve \
           -var="commit_sha=${{ github.sha }}"

        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
          TF_VAR_reddit_client_id: ${{ secrets.REDDIT_CLIENT_ID }}
          TF_VAR_reddit_client_secret: ${{ secrets.REDDIT_CLIENT_SECRET }}
